package LaptopIntro;

public class Requirments 
{
//  REQUIRMENTS:	
//=====================================================================
//	LAPTOP---> ID,BRAND,OS,PROCESSOR,RAM,PRICE,COLOUR,DISPLAY SIZE
//	SAVE LAPTOP(LAPTOP LAPTOP)
//	UPDATE LAPTOP(LAPTOP L)
//	DELTE LAPTOP(INT ID)
//	FETCH LAPTOP(INT ID)
//	FETCH ALL LAPTOP()
//	FETCH LAPTOP BY BRAND(STRING BRNAD)
//	FETCH LAPTOP BY RAM AND PRICE (INT RAM,DOUBLE PRICE)
//	FETCH LAPTOP BY PRICE(DOUBLE PRICE)
}
